defaults:
  - _self_

width: 47.3861
width_pixel: 1680
height: 29.6163
height_pixel: 1050
distance: 47

subject_number: 10
subjects: [1,2,3,4,5,6,7,8,9,10]

dir: C:\datasets\COCO-Search18
conditions:
  - "TP"
  - "TA"

# CCS18 categories
categories:
  - "bottle"
  - "bowl"
  - "car"
  - "chair"
  - "clock"
  - "cup"
  - "fork"
  - "keyboard"
  - "knife"
  - "laptop"
  - "microwave"
  - "mouse"
  - "oven"
  - "potted plant"
  - "sink"
  - "stop sign"
  - "toilet"
  - "tv"

json:
  - coco_search18_fixations_TA_trainval.json
  - coco_search18_fixations_TP_train_split1.json
  - coco_search18_fixations_TP_validation_split1.json
